spring:
  application:
    name: fmall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #SpringSession将session存入redis
  session:
    store-type: redis
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: fmall.com
server:
  port: 20000
  servlet:
    #session过期时间30分钟
    session:
      timeout: 30m
