server:
  port: 40000

spring:
  application:
    name: fmall-cart
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  redis:
    host: fmall.com
    port: 6379
# 线程池相关配置
fmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10