server:
  port: 13000
spring:
  application:
    name: fmall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: fmall.com
    port: 6379
  #用redis存储分布式session
  session:
    store-type: redis

management:
  endpoints:
    web:
      exposure:
        include: '*'
