spring:
  application:
    name: fmall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #redis相关配置
  redis:
    host: 169.254.122.40
    port: 6379
  #springsession将session存储到redis
  session:
    store-type: redis
  #关闭thymeleaf缓存
  thymeleaf:
    cache: false
server:
  port: 12000