spring:
  application:
    name: fmall-third-party
  cloud:
    #配置阿里云对象存储
    alicloud:
      access-key: XXXXXX
      secret-key: XXXX
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: fmall8080
      #短信相关配置
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        templateId: 908e94ccf08b4476ba6c876d13f084ad
        smsSignId: XXXXX
        appcode: XXXX
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 30000